/**
 * The catalog service joins live Shopify pricing onto the curated
 * controllerSpecs.json entries to produce the `Controller[]` the UI consumes.
 *
 * Caching strategy: stale-while-revalidate against `localStorage`.
 *   - First load: returns whatever is in the cache immediately if present
 *     (fresh OR stale), then revalidates against Shopify in the background.
 *   - When the cache is missing entirely, the bundled `fallbackCatalog.json`
 *     is used as the bootstrap so the UI never renders empty.
 *   - Fetch failures don't surface as rejection — they leave the cache
 *     untouched and set `error` on the returned snapshot.
 */

import controllerSpecsRaw from '../../data/controllerSpecs.json'
import fallbackCatalog from '../../data/fallbackCatalog.json'
import type { Controller } from '../../types/controller'
import {
  fetchControllerProducts,
  type FetchControllerProductsOptions,
} from '../shopify'
import {
  defaultStorage,
  isCacheStale,
  readCache,
  writeCache,
  type CachedCatalog,
  type CatalogStorage,
} from './cache'
import { curatedSpecsFromRaw, mergeCatalog } from './merge'

export type { CachedCatalog, CatalogStorage } from './cache'
export { mergeCatalog, mergeOne } from './merge'
export type CatalogStatus = 'loading' | 'ready' | 'error'

export type CatalogSnapshot = {
  status: CatalogStatus
  controllers: Controller[]
  fetchedAt: number | null
  /**
   * `true` when `controllers` came from the cache or bundled fallback rather
   * than a fresh Shopify fetch. The UI uses this to show a "showing cached
   * prices from <time>" banner.
   */
  fromCache: boolean
  error: Error | null
}

/**
 * Bundled bootstrap catalog used when no localStorage cache exists yet.
 * Regenerated by `scripts/refresh-fallback.ts` (`pnpm refresh-fallback`).
 */
export function getFallbackCatalog(): CachedCatalog {
  return fallbackCatalog as CachedCatalog
}

export type LoadCatalogOptions = FetchControllerProductsOptions & {
  storage?: CatalogStorage | null
  now?: () => number
}

/**
 * One-shot load — fetches fresh, merges, persists, returns. Use the SWR
 * generator below for the UI.
 */
export async function loadCatalog(
  options: LoadCatalogOptions = {},
): Promise<CatalogSnapshot> {
  const storage = options.storage ?? defaultStorage()
  const now = options.now ?? (() => Date.now())
  try {
    const products = await fetchControllerProducts(options)
    const specs = curatedSpecsFromRaw(controllerSpecsRaw)
    const controllers = mergeCatalog(products, specs)
    const fetchedAt = now()
    writeCache({ fetchedAt, controllers }, storage)
    return {
      status: 'ready',
      controllers,
      fetchedAt,
      fromCache: false,
      error: null,
    }
  } catch (error) {
    const cached = readCache(storage) ?? getFallbackCatalog()
    return {
      status: 'error',
      controllers: cached.controllers,
      fetchedAt: cached.fetchedAt,
      fromCache: true,
      error: error instanceof Error ? error : new Error(String(error)),
    }
  }
}

/**
 * Stale-while-revalidate iterator. Yields up to two snapshots:
 *   1. Snapshot from cache (or fallback) so the UI paints immediately.
 *   2. Snapshot from the live fetch (or an `error` snapshot if the fetch
 *      fails — the UI keeps the cache visible).
 *
 * If the cache is fresh, only the first snapshot is yielded.
 */
export async function* loadCatalogSWR(
  options: LoadCatalogOptions = {},
): AsyncGenerator<CatalogSnapshot> {
  const storage = options.storage ?? defaultStorage()
  const now = options.now ?? (() => Date.now())
  const cached = readCache(storage)
  const seed = cached ?? getFallbackCatalog()

  yield {
    status: 'ready',
    controllers: seed.controllers,
    fetchedAt: seed.fetchedAt,
    fromCache: true,
    error: null,
  }

  if (cached && !isCacheStale(cached, now())) return

  yield await loadCatalog({ ...options, storage, now })
}
